# Generated by Django 4.1.4 on 2023-11-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_mod', models.CharField(max_length=100)),
                ('text_of_mod', models.CharField(max_length=1000)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relation.comment')),
            ],
        ),
    ]
