# Generated by Django 4.1.4 on 2023-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_remove_mod_comments_comment_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mod',
        ),
        migrations.AddField(
            model_name='mod',
            name='comments',
            field=models.ManyToManyField(to='relation.comment'),
        ),
    ]
